### ISSUE TITLE
Multi-fast5 doesn't seem to work

### ISSUE THREAD

**Issue by jkbonfield** [AlexanderVi/ont2cram#14]
This is a file produced from guppy, starting from a multi-fast5 file:

```
./bin/guppy_basecaller -c data/dna_r9.4.1_450bps_fast.cfg --fast5_out -i in2 -s out2.fast
```

ont2cram can read the out2.fast/*.fast5 file (there's only one), but cram2ont fails:

```
1it [00:01,  1.32s/it]
Traceback (most recent call last):
  File "./cram2ont", line 5, in <module>
    sys.exit(cram2ont.main())
  File "/home/ubuntu/ont2cram/cram2ont.py", line 171, in main
    run( args.inputfile, args.outputdir )
  File "/home/ubuntu/ont2cram/cram2ont.py", line 164, in run
    cram_to_fast5( input_file, output_dir )
  File "/home/ubuntu/ont2cram/cram2ont.py", line 116, in cram_to_fast5
    f.create_dataset( "/Analyses/Basecall_1D_000/BaseCalled_template/Fastq", data=fastq_lines , maxshape=(None))
  File "/usr/lib/python3/dist-packages/h5py/_hl/group.py", line 109, in create_dataset
    self[name] = dset
  File "/usr/lib/python3/dist-packages/h5py/_hl/group.py", line 277, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-qzs83i/h5py-2.7.1/h5py/_objects.c:2847)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-qzs83i/h5py-2.7.1/h5py/_objects.c:2805)
  File "h5py/h5o.pyx", line 202, in h5py.h5o.link (/build/h5py-qzs83i/h5py-2.7.1/h5py/h5o.c:3899)
RuntimeError: Unable to create link (name already exists)
```

The error appears to be due to h5py `create_dataset` refusing to modify an existing object.   There is a query regarding this error here: https://groups.google.com/forum/#!topic/h5py/C5KFYVlCt0I with a pointer to using the `maxshape=(None)` attribute here: http://docs.h5py.org/en/latest/high/dataset.html#resizable-datasets however this doesn't fix things.

**Comment by jkbonfield** [comment]
The test data multi-fast5 does work, but the format is different.

My data has header lines such as (redacted):

```
@<HEXUUID> runid=<HEXUUID> sampleid=SAMPLE_16Kb_final read=11422 ch=1889 start_time=<TIME>
```

These full names actually make it into the CRAM RNAMES, so they're around 160 chars long including spaces.  I'm wondering if this is the cause.  I'll experiment.  Is it intentional that all this ends up in the name field?

**Comment by AlexanderVi** [comment]
No it is not intentional, looks like a bug. Only <HEXUUID> ( which is read id ) supposed to be written to CRAM. Could you please provide a small sample to reproduce this problem? Thanks.

**Comment by AlexanderVi** [comment]
No it is not intentional, looks like a bug. Only HEXUUID( which is read id ) supposed to be written to CRAM. Could you please provide a small sample to reproduce this problem? Thanks.
