### ISSUE TITLE
Error with multiread fast5 from guppy 3.4.1

### ISSUE THREAD

**Issue by wdecoster** [AlexanderVi/ont2cram#19]
Hi,

I just created a small fast5 file with the latest guppy 3.4.1. I shared it on google drive: https://drive.google.com/file/d/1H4xiOw9Q4bbTBbunlJX2Be1YbPoQC_qh/view?usp=sharing
I used methylation aware basecalling (with `-c dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg`)

Running ont2cram (fresh installation, v0.0.1) returns this:

```
Loading Fast5 from: '/home/wdecoster/methylation/NA19240/guppy_mAware/workspace'
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.76s/it]
Writing CRAM to: '/home/wdecoster/methylation/NA19240/guppy_mAware/CD74.cram'
  0%|                                                                                                                                                      | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/wdecoster/miniconda3/bin/ont2cram", line 4, in <module>
    __import__('pkg_resources').run_script('ont2cram==0.0.1', 'ont2cram')
  File "/home/wdecoster/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/wdecoster/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/home/wdecoster/miniconda3/lib/python3.7/site-packages/ont2cram-0.0.1-py3.7.egg/EGG-INFO/scripts/ont2cram", line 5, in <module>
  File "/home/wdecoster/miniconda3/lib/python3.7/site-packages/ont2cram-0.0.1-py3.7.egg/ont2cram.py", line 392, in main
  File "/home/wdecoster/miniconda3/lib/python3.7/site-packages/ont2cram-0.0.1-py3.7.egg/ont2cram.py", line 378, in run
  File "/home/wdecoster/miniconda3/lib/python3.7/site-packages/ont2cram-0.0.1-py3.7.egg/ont2cram.py", line 326, in write_cram
  File "/home/wdecoster/miniconda3/lib/python3.7/site-packages/h5py/_hl/group.py", line 565, in visititems
    return h5o.visit(self.id, proxy)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 355, in h5py.h5o.visit
  File "h5py/defs.pyx", line 1641, in h5py.defs.H5Ovisit_by_name
  File "h5py/h5o.pyx", line 302, in h5py.h5o.cb_obj_simple
  File "/home/wdecoster/miniconda3/lib/python3.7/site-packages/h5py/_hl/group.py", line 564, in proxy
    return func(name, self[name])
  File "/home/wdecoster/miniconda3/lib/python3.7/site-packages/ont2cram-0.0.1-py3.7.egg/ont2cram.py", line 296, in process_attrs
  File "/home/wdecoster/miniconda3/lib/python3.7/site-packages/ont2cram-0.0.1-py3.7.egg/ont2cram.py", line 280, in process_dataset
TypeError: an integer is required (got type list)
```

Is there something else you want me to try?

Thanks,
Wouter

**Comment by AlexanderVi** [comment]
Did some debugging : turns out this is a limitation of current implementation. It expects all datasets with multiple columns to have column names. In the provided sample the ModBaseProbs dataset violates this requirement.
![image](https://user-images.githubusercontent.com/26434252/70062743-a9513b80-15f7-11ea-999c-69b88aac5d51.png)

Here is what expected:

![image](https://user-images.githubusercontent.com/26434252/70063633-2b8e2f80-15f9-11ea-8fc4-d7bf95952e7f.png)

All the columns stored in CRAM individually ( as separate tags ) and the since number of tags is limited (~1500) very wide datasets can not be stored

**Comment by wdecoster** [comment]
I don't know if ONT (tagging @fbrennen) intends to keep ModBaseProbs as such or has other ideas on how to encode the probability of modifications for future formats?

And @jkbonfield Do you have thoughts about this?

**Comment by AlexanderVi** [comment]
We are currently considering switching to ont_fast5_api and saving to CRAM only essential datasets/attributes. Do you think ModBaseProbs is worth saving it into CRAm at all?

**Comment by wdecoster** [comment]
Maybe not in its current representation, but putting modified nucleotides (methylcytosine,...) in CRAM would be very useful.

**Comment by fbrennen** [comment]
@wdecoster we're going to offer the new sam format as a way of storing methylated base information soon -- check that out [here](https://github.com/samtools/hts-specs/pull/418/). I imagine we'll offer that in parallel to putting the information in fast5 files, though it's not set yet -- if you've got a preference pop into the community and let's talk about it.

**Comment by fbrennen** [comment]
@AlexanderVi in reference to this particular issue there are a bunch of tables in more recent fast5 files that don't have column names and are not compound datatype tables, such as the posterior output, trace, and move tables (those are all matrices of 1-2 dimensions).
